#include "sem_script.h"

/*NOTE: WRITE YOUR SCRIPT IN THE FOLLOWING FUNCTION.
  FINISH WITH ctrl+c IN THE OPEN TERMINAL.
  IF YOU NEED TO CHECK ERROR CORRECTION AFTER INJECTION,
  LAUNCH A NEW wait_resp() FUNCTION TO RECEIVE THE RESPONSE.
*/
void my_sem_script (){

}
